### ISSUE TITLE
Build error when adding this moudule

### ISSUE THREAD

**Issue by ShahinRockstarsIT** [harlan-zw/nuxt-seo-kit#23]
### Describe the bug

After adding this module the build on the server fails. locally it builds ok. I don't know if it has something to do with render.com or the package.

### System Info

```Shell
Feb 3 02:31:32 PM  ==> Checking out commit aed18fecb5f658ffa0aecfa586905f55bc931f40 in branch seo-kit
Feb 3 02:31:34 PM  ==> Downloading cache...
Feb 3 02:31:50 PM  ==> Transferred 337MB in 9s. Extraction took 5s.
Feb 3 02:31:52 PM  ==> Running build command 'npm install && npm run build;'...
Feb 3 02:32:11 PM  
Feb 3 02:32:11 PM  > undefined postinstall /opt/render/project/src
Feb 3 02:32:11 PM  > nuxt prepare
Feb 3 02:32:11 PM  
Feb 3 02:32:11 PM  Nuxi 3.1.2
Feb 3 02:32:27 PM  
Feb 3 02:32:27 PM   ERROR  Maximum call stack size exceeded
Feb 3 02:32:27 PM  
Feb 3 02:32:27 PM    at node_modules/jiti/dist/jiti.js:1:245789
Feb 3 02:32:27 PM    at _interopDefault (node_modules/jiti/dist/jiti.js:1:246108)
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248885)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:8:15
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/mlly/dist/index.cjs:14:18
Feb 3 02:32:27 PM    at jiti (node_modules/jiti/dist/jiti.js:1:248448)
Feb 3 02:32:27 PM    at node_modules/pkg-types/dist/index.mjs:3:13
Feb 3 02:32:27 PM  
Feb 3 02:32:27 PM  npm ERR! code ELIFECYCLE
Feb 3 02:32:27 PM  npm ERR! errno 1
Feb 3 02:32:27 PM  npm ERR! undefined postinstall: `nuxt prepare`
Feb 3 02:32:27 PM  npm ERR! Exit status 1
Feb 3 02:32:27 PM  npm ERR!
Feb 3 02:32:27 PM  npm ERR! Failed at the undefined postinstall script.
Feb 3 02:32:27 PM  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
Feb 3 02:32:27 PM  
Feb 3 02:32:27 PM  npm ERR! A complete log of this run can be found in:
Feb 3 02:32:27 PM  npm ERR!     /opt/render/.cache/_logs/2023-02-03T13_32_27_799Z-debug.log
Feb 3 02:32:27 PM  ==> Build failed 😞
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by ShahinRockstarsIT** [comment]
I solved this issue.
Render.com has `14.17.0` as the default Node version, by increasing the node version to 18.x build was successfully.

**Comment by StevenJPx2** [comment]
I'm still facing this issue with a fresh Nuxt project. Not sure why everytime I use it it has this issue. I switched to node 16, 18 and none work. They give the above error. 

Any ways to solve this @harlan-zw?
