### ISSUE TITLE
"root is not defined" error after upgrade to nuxt 3.2.2

### ISSUE THREAD

**Issue by ffoerster** [harlan-zw/nuxt-seo-kit#36]
### Describe the bug

After updating Nuxt to 3.2.2, i am getting the following error message (on _yarn dev_ as well as on _yarn build_ ):

`ERROR  Cannot start nuxt:  root is not defined                                                           14:14:54

  at config (file://node_modules/@unhead/addons/dist/shared/addons.ba318fee.mjs:73:9)
  at runConfigHook (file://node_modules/vite/dist/node/chunks/dep-ca21228b.js:62423:31)
  at async resolveConfig (file://node_modules/vite/dist/node/chunks/dep-ca21228b.js:61924:14)
  at async Module.createServer (file://node_modules/vite/dist/node/chunks/dep-ca21228b.js:61201:20)
  at async buildClient (file://node_modules/@nuxt/vite-builder/dist/shared/vite-builder.a46e9c8e.mjs:456:24)
  at async bundle (file://node_modules/@nuxt/vite-builder/dist/shared/vite-builder.a46e9c8e.mjs:1070:3)
  at async build (file://node_modules/nuxt/dist/index.mjs:2692:5)
  at async Promise.all (index 1)
  at async load (file://node_modules/nuxi/dist/chunks/dev.mjs:6824:9)
  at async Object.invoke (file://node_modules/nuxi/dist/chunks/dev.mjs:6878:5)`

### Reproduction

https://stackblitz.com/edit/github-7trkbw?file=package.json

### System Info

```Shell
System:
    OS: Linux 5.0 undefined
    CPU: (8) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 0 Bytes / 0 Bytes
    Shell: 1.0 - /bin/jsh
  Binaries:
    Node: 16.14.2 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.17.0 - /usr/local/bin/npm
```

### Used Package Manager

npm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/harlan-zw/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by harlan-zw** [comment]
Hey @ffoerster, thanks for the issue!

Should be fixed now, please try v1.3.0 and let me know if you have any problems.
