### ISSUE TITLE
Install nuxt-seo-kit, get following warning.

### ISSUE THREAD

**Issue by sendking** [harlan-zw/nuxt-seo-kit#50]
### Describe the bug

<img width="950" alt="image" src="https://user-images.githubusercontent.com/12857833/230861287-519d9991-616b-4d65-be1c-fb9e71bc687f.png">

package.json
```
{
  "name": "wasu_com_cn",
  "description": "wasu.com.cn website",
  "private": false,
  "scripts": {
    "dev": "nuxt dev --port 6636 --dotenv env/.env.dev",
    "dev:prod": "nuxt dev --port 6636 --dotenv env/.env.prod",
    "build": "nuxt build --dotenv env/.env.dev",
    "build:prod": "nuxt build --dotenv env/.env.prod",
    "generate": "nuxt generate",
    "preview": "nuxt preview",
    "postinstall": "nuxt prepare",
    "serve": "esno .output/server/index.mjs",
    "p:ish": "pnpm install --shamefully-hoist",
    "p:up": "pnpm up",
    "lint": "eslint --fix .",
    "prepare": "husky install",
    "deploy-dev": "npm i --registry=https://registry.npmmirror.com && npm run build && npx pm2 start",
    "deploy-prod": "npm i --registry=https://registry.npmmirror.com && npm run build:prod && npx pm2 start"
  },
  "devDependencies": {
    "@intlify/nuxt3": "^0.2.4",
    "@nuxt/types": "^2.16.0",
    "@nuxtjs/eslint-config-typescript": "^12.0.0",
    "@nuxtjs/i18n": "^8.0.0-beta.9",
    "@pinia-plugin-persistedstate/nuxt": "^1.1.1",
    "@pinia/nuxt": "^0.4.7",
    "@types/aos": "^3.0.4",
    "@types/crypto-js": "^4.1.1",
    "@vueuse/nuxt": "^9.6.0",
    "esbuild": "^0.17.11",
    "eslint": "^8.33.0",
    "husky": "^8.0.0",
    "less": "^4.1.3",
    "nuxt": "^3.3.1",
    "nuxt-windicss": "^2.5.5",
    "typescript": "^4.9.5",
    "unplugin-vue-components": "^0.22.11"
  },
  "dependencies": {
    "@vant/nuxt": "^1.0.0",
    "@videojs-player/vue": "^1.0.0",
    "@vueuse/core": "^9.13.0",
    "aos": "^2.3.4",
    "axios": "^1.3.4",
    "crypto-js": "^4.1.1",
    "nuxt-seo-kit": "^1.3.4",
    "pinia": "^2.0.33",
    "pinia-plugin-persistedstate": "^3.0.1",
    "swiper": "^8.4.7",
    "vant": "^4.0.11",
    "video.js": "^7.0.4",
    "vue-awesome-swiper": "^5.0.1"
  },
  "__npminstall_done": false
}

```

**Comment by sendking** [comment]
```npm i nuxt-seo-kit ```
Got following error.
<img width="593" alt="image" src="https://user-images.githubusercontent.com/12857833/231035071-86dadc30-0b6b-45cc-87da-a19147b1df9b.png">

**Comment by harlan-zw** [comment]
Hey, guess you were able to solve this? These composables shouldn't be added within the latest version of nuxt-unhead and that version of Nuxt.

**Comment by sendking** [comment]
> Hey, guess you were able to solve this? These composables shouldn't be added within the latest version of nuxt-unhead and that version of Nuxt.

1. I solved by ```npm i nuxt-seo-kit@1.3.4``` but get the warning of issues's title.
2. I want ```npm i nuxt-seo-kit``` to install the latest version of nuxt-seo-kit but failed.
3. My npm registry is ```https://registry.npmmirror.com```. When i `npm i --registry="https://registry.npmjs.org/"` can install the latest version of nuxt-seo-kit.
4. ```npm publish --registry=https://registry.npmmirror.com/``` may help me😊.

**Comment by sendking** [comment]
> 

0 verbose cli /Users/lishaokai/.nvm/versions/node/v16.15.0/bin/node /Users/lishaokai/.nvm/versions/node/v16.15.0/bin/npm
1 info using npm@9.6.2
2 info using node@v16.15.0
3 timing npm:load:whichnode Completed in 1ms
4 timing config:load:defaults Completed in 1ms
5 timing config:load:file:/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/npmrc Completed in 0ms
6 timing config:load:builtin Completed in 0ms
7 timing config:load:cli Completed in 0ms
8 timing config:load:env Completed in 1ms
9 timing config:load:file:/Users/lishaokai/workspace/wasu/wasu_com_cn/.npmrc Completed in 0ms
10 timing config:load:project Completed in 0ms
11 timing config:load:file:/Users/lishaokai/.npmrc Completed in 1ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/Users/lishaokai/.nvm/versions/node/v16.15.0/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 0ms
15 timing config:load:setEnvs Completed in 1ms
16 timing config:load Completed in 4ms
17 timing npm:load:configload Completed in 4ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 0ms
20 verbose title npm i
21 verbose argv "i"
22 timing npm:load:setTitle Completed in 5ms
23 timing config:load:flatten Completed in 1ms
24 timing npm:load:display Completed in 2ms
25 verbose logfile logs-max:10 dir:/Users/lishaokai/.npm/_logs/2023-04-12T08_20_30_511Z-
26 verbose logfile /Users/lishaokai/.npm/_logs/2023-04-12T08_20_30_511Z-debug-0.log
27 timing npm:load:logFile Completed in 2ms
28 timing npm:load:timers Completed in 0ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 14ms
31 timing arborist:ctor Completed in 0ms
32 silly logfile start cleaning logs, removing 1 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 234ms
35 timing idealTree:userRequests Completed in 0ms
36 silly idealTree buildDeps
37 silly fetch manifest nuxt-seo-kit@^1.3.6
38 timing arborist:ctor Completed in 0ms
39 http fetch GET 200 https://registry.npmmirror.com/nuxt-seo-kit 197ms (cache hit)
40 silly placeDep ROOT nuxt-seo-kit@1.3.6 REPLACE for:  want: ^1.3.6
41 silly fetch manifest nuxt-unhead@^1.4.15
42 http fetch GET 200 https://registry.npmmirror.com/nuxt-unhead 3ms (cache hit)
43 timing idealTree:#root Completed in 213ms
44 silly placeDep node_modules/nuxt-seo-kit nuxt-unhead@ OK for: nuxt-seo-kit@1.3.6 want: ^1.4.15
45 timing idealTree:node_modules/nuxt-seo-kit Completed in 1ms
46 timing idealTree:node_modules/nuxt-seo-kit/node_modules/nuxt-unhead Completed in 0ms
47 timing idealTree:buildDeps Completed in 214ms
48 timing idealTree:fixDepFlags Completed in 4ms
49 timing idealTree Completed in 452ms
50 timing command:i Completed in 455ms
51 verbose type range
52 verbose stack nuxt-unhead: No matching version found for nuxt-unhead@^1.4.15.
52 verbose stack     at module.exports (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/npm-pick-manifest/lib/index.js:209:23)
52 verbose stack     at RegistryFetcher.manifest (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/pacote/lib/registry.js:119:22)
52 verbose stack     at async Promise.all (index 0)
52 verbose stack     at async Arborist.[buildDepStep] (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:1044:5)
52 verbose stack     at async Arborist.buildIdealTree (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/build-ideal-tree.js:207:7)
52 verbose stack     at async Promise.all (index 1)
52 verbose stack     at async Arborist.reify (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:159:5)
52 verbose stack     at async Install.exec (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/lib/commands/install.js:146:5)
52 verbose stack     at async module.exports (/Users/lishaokai/.nvm/versions/node/v16.15.0/lib/node_modules/npm/lib/cli.js:134:5)
53 verbose cwd /Users/lishaokai/workspace/wasu/wasu_com_cn
54 verbose Darwin 21.6.0
55 verbose node v16.15.0
56 verbose npm  v9.6.2
57 error code ETARGET
58 error notarget No matching version found for nuxt-unhead@^1.4.15.
59 error notarget In most cases you or one of your dependencies are requesting
59 error notarget a package version that doesn't exist.
60 verbose exit 1
61 timing npm Completed in 477ms
62 verbose unfinished npm timer reify 1681287630532
63 verbose unfinished npm timer reify:loadTrees 1681287630533
64 verbose code 1
65 error A complete log of this run can be found in:
65 error     /Users/lishaokai/.npm/_logs/2023-04-12T08_20_30_511Z-debug-0.log
